hal: audio_extn: fix launch_power_policy method call
vendor/qcom/opensource/audio-hal/primary-hal/hal/audio_extn/audio_extn.c:6604:24: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototyp
e]
    launch_power_policy(init_config);
                       ^
aurguement is not required.