hal: msm8974: platform.c fix acdb_init method call
vendor/qcom/opensource/audio-hal/primary-hal/hal/msm8974/platform.c:3023:36: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
        result = my_data->acdb_init(snd_card_name, cvd_version, key);
                       ^

aurguement is not required.